name: clicker
description: "The clicker you alsways wanted in your dreams."
publish_to: "none"
version: 0.0.1
environment: { sdk: ">=3.4.0 <4.0.0" }
flutter: { uses-material-design: true }

dependencies:
  async: ^2.11.0
  bloc: ^8.1.4
  collection: ^1.18.0
  flutter: { sdk: flutter }
  flutter_bloc: ^8.1.5
  nes_ui: ^0.20.0

dev_dependencies:
  flutter_test: { sdk: flutter }
  very_good_analysis: ^5.1.0
